### ISSUE TITLE
Can't mount and detect CD-ROM drives

### ISSUE THREAD

**Issue by salmanaligeek** [mbusb/multibootusb#108]
Hi,

First of all, I really liked your work because there is no tool like YUMI on Linux, I appreciate you created one. I successfully added three ISOs to my USB but unable to install any Linux distribution. Every distribution stuck at this error:
Can't mount and detect CD-ROM drives.
I already tried to unplug and plugin the USB but same error. I don't want to think this awesome tool is useless for me.

Regards,
Salman Ali

**Comment by mbusb** [comment]
Thanks for trying.  

The main job of multibootusb is to create live Linux. 

The error you are getting may be due to install script shipped by debian looking for OS data from CDROM instead of USB device. To overcome, you may want to link your USB mount point to your CDROM and proceed with insulation.  But this is my guess. If you create Live USB using 'ISO Imager' then everything should work properly as it behave like a CDROM.

> I don't want to think this awesome tool is useless for me.

I don't think it is going to be useless as it also helps producing live usb of different distors.

**Comment by salmanaligeek** [comment]
`I don't think it is going to be useless as it also helps producing live usb of different distors.
`
I didn't it is useless, I was saying that I don't want to think it like that because it is good.

**Comment by mbusb** [comment]
Not possible to fix under project scope.
