### ISSUE TITLE
Not work with VectorLinux 7.xxx

### ISSUE THREAD

**Issue by DarthMoulByte** [mbusb/multibootusb#259]
all time say corrupted or the usb freezer

**Comment by mbusb** [comment]
What info am I supposed to infer from your post?

Where is the log file?

On 23-Jan-2018 9:33 AM, "DarthMoulByte" <notifications@github.com> wrote:

all time say corrupted or the usb freezer

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mbusb/multibootusb/issues/259>, or mute the thread
