### ISSUE TITLE
QEMU -enable-kvm is used for Windows

### ISSUE THREAD

**Issue by JakubFojtik** [mbusb/multibootusb#369]
In  [qemu.py#L51](https://github.com/mbusb/multibootusb/blob/master/scripts/qemu.py#L51) there are two functions that call QEMU and only one cares about platform. The other passes the linux-only _-enable-kvm_ which causes QEMU to fail.

The checks are already implemented in the other function [qemu.py#L101](https://github.com/mbusb/multibootusb/blob/master/scripts/qemu.py#L101)

BTW I googled that Windows have an analogic acceleration feature [-enable-hax](https://www.qemu.org/2017/11/22/haxm-usage-windows/), but only on Intel CPUs

**Comment by shinji-s** [comment]
Thank you for reporting. This problem should has been resovled by commit https://github.com/mbusb/multibootusb/commit/fc56319187608de3ae27aa35c697b34f91307287.
Please close this issue for now  and reopen if you find otherwise when you try a version that includes the commit.

As for HAXM support , if you use devel branch and set qemu_use_haxm to True in config.py, then '--accel hax' will be added to the qemu command line. But I found out that recent QEMU versions that support HAXM exhibit extremely low I/O throughput in my environment and I gave up using it.

**Comment by JakubFojtik** [comment]
Ok thanks.
