### ISSUE TITLE
Does not list installed distros and unable to re-install it

### ISSUE THREAD

**Issue by carestad** [mbusb/multibootusb#48]
When installing an ISO with 7.5.0 it does not seem to complete and list the distro afterwords. The directory exists though.

When trying to re-create it, the following error appears:

![image](https://cloud.githubusercontent.com/assets/65263/15679057/bd2a38b2-2750-11e6-8fd2-c51605bcffc1.png)

Syslinux config also does not list it, unfortunately.

**Comment by carestad** [comment]
I am using Ubuntu 15.10 x64 by the way.

**Comment by mbusb** [comment]
It seems that previous install extracted ISO but didn't complete the
syslinux install. That's why it says the distro is already installed. You
can remove the previous distro directory and proceed again for new install.

Meanwhile you can try the latest code. The main bug causing the Ubuntu
install failure is fixed in the latest source.

**Comment by carestad** [comment]
Will the source version be released soon and .deb package created?

**Comment by carestad** [comment]
By the way, it works if I use version 7.4.

**Comment by mbusb** [comment]
Fixed in the latest version. Closing the issue.
