### ISSUE TITLE
Debian: No common CD-ROM drive was detected

### ISSUE THREAD

**Issue by bagage** [mbusb/multibootusb#85]
### Issue

Blocked when installing Debian to second step *Detect and mount CD-ROM*.

I'm trying to install a [Debian net-install ISO](http://cdimage.debian.org/debian-cd/8.6.0/amd64/bt-cd/debian-8.6.0-amd64-netinst.iso.torrent) using master, but it fails at this step. According to a comment on [cobbler#1518](https://github.com/cobbler/cobbler/issues/1518#issuecomment-209011644):

nacc:
> I think I recalled now what is needed. When you use Debian or Ubuntu (in my experience), you need to replace the kernel and initrd from the full ISO with that from the netinstaller. Can you verify this fixes the issue?
So, what I'm suggesting is use the *DVD-1.iso and then copy over to /var/lib/cobbler appropriately the initrd & kernel from the corresponding netinst.iso.

I also tried with [Debian stable ISO](http://cdimage.debian.org/debian-cd/8.6.0/amd64/bt-cd/debian-8.6.0-amd64-CD-1.iso.torrent) or [Debian live one](http://cdimage.debian.org/debian-cd/8.6.0/amd64/bt-cd/debian-8.6.0-amd64-xfce-CD-1.iso.torrent), but still facing the same issue.

### Workaround

~~None found yet, except of using another OS (windows, archlinux work OK) or maybe another USB installer software.~~ See comment https://github.com/mbusb/multibootusb/issues/85#issuecomment-284742381

**Comment by mbusb** [comment]
There is one more workaround within multibootusb itself. Make bootable USB from imager option. Let me know if you find any other solution exist.

**Comment by bagage** [comment]
@mbusb: I tried that but it doesn't work. I did:

1. Install the Debian netinstall ISO via imager ISO option
2. Run qemu from CLI (due to #88): `
3. Select "Install" (and/or "Graphical install", same output), then press [enter], [enter], [enter].
4. Then "No common CD-ROM drive was detected" appears.

**Comment by bagage** [comment]
Anyone succeeded to install Debian via multibootusb? @mbusb?

**Comment by bagage** [comment]
I finally succeeded using the following work-around (for amd64):

1. Download debian netinstall from [debian-installer website](https://www.debian.org/devel/debian-installer/): [debian ISO for amd64](http://cdimage.debian.org/cdimage/stretch_di_rc2/amd64/iso-cd/debian-stretch-DI-rc2-amd64-netinst.iso).
2. Download [hd-media files (bootloader and kernel files)](http://ftp.nl.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/)  for **amd64** (i386 one won't work). Must get [initrd.gz](http://ftp.nl.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/initrd.gz) as well as [vmlinuz](http://ftp.nl.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/vmlinuz).
3. Use `multibootusb` to create the Debian entry, as usual
4. Then mount the partition, say in `/mnt`.
5. Replace vmlinuz and initrd.gz with the hd-media ones (assuming they are in the same folder as the current prompt): 
    ```
    find /mnt/multibootusb/debian-7.8.0-amd64-netinst/ -name vmlinuz -exec sudo cp vmlinuz {} \;
    find /mnt/multibootusb/debian-7.8.0-amd64-netinst/ -name initrd.gz -exec sudo cp initrd.gz {} \;
    ```
6. Copy debian ISO on the USB stick direcly: `cp debian-stretch-DI-rc2-amd64-netinst.iso /mnt/multibootusb/`. You can also put it in `/mnt/multibootusb/debian-7.8.0-amd64-netinst/`, but in that case Debian installer will yield that it could not find the ISO and will ask if you want it to search more. You have to hit Yes.

**Comment by ierpe** [comment]
Hi,

I have this problem on a (very) old laptop, i386 arch.
The setup starts but "cannot mount the CD-ROM".
Any workaround would be appreciated :)

**Comment by mbusb** [comment]
Documented this in official site  [http://multibootusb.org/page_faq/#debiann-no-common-cd-rom-drive-was-detected](http://multibootusb.org/page_faq/#debiann-no-common-cd-rom-drive-was-detected)

Closing the issue.

**Comment by Erudition** [comment]
Better workaround:
For many installers, mounting the flash drive (say, `/dev/sdb1`) to `/cdrom` does the trick. However, in this case that still fails because the iso contents are not directly on the drive but in a subdirectory. So what if we instead mount that subdirectory at `/cdrom`?
We'll have to mount the drive itself somewhere else. For example
`mount /dev/sdb1 /mnt/flash`
Then, we can "mount" the folder with the installer contents onto /cdrom by making a symlink:
`ln -s /mnt/flash/multibootusb/nameofdebianimagehere/ /cdrom`
That's it!

Notes:
- This can be accomplished in the installer menu item for launching a shell session, which will then return to the installer, or you can hit Ctrl+Alt+F(5 or any other number) to switch to a tty session, then return by looking for the tty the installer was on.
- Obviously you should `ls /mnt/flash/multibootusb/` to see what your target folder should be. Also, tab completion is your friend!
- You may need to `rm /cdrom` first so you can replace it with the symlink.
- Don't forget the `-s`, hardlinks can't cross devices so this must be a symlink.

**This issue should be reported to upstream (debian). Other distros work fine without this treatment.**

**Comment by thorsummoner** [comment]
@Erudition Can i get a link to the debian but report?

**Comment by robertwolter** [comment]
I tried to use the suggested workarounds, but they didn't work for me.
I tested:
debian-9.2.1-amd64-netinst.iso
debian-live-9.2.0-amd64-xfce+nonfree.iso

I can't mount any existing partition though they are shown by blkid.
ls -la /dev/sdb* shows that /dev/sdb and the multibootusb partition /dev/sdb1 do exist.
Using the graphic installer I tried in a shell:
mkdir /flash
mount -t ext4 /dev/sdb1 /flash
I only got an error message that the device does not exist. The mount command fails completely.

**Comment by thorsummoner** [comment]
i don't know if i said so, but using the full install cd images was a
suitable work around for me.

**Comment by robertwolter** [comment]
Now the reason is clear: 
The mount command simply can't work because the module ext4 is missing in busybox in all Debian ISOs.

**Comment by tripLr** [comment]
is there a script we can put in the usb drive during boot that will tell grub to run the special mount for the debian disto's ? debian iso installed onto a single usb boot seem to work fine. whats the difference, I am new to this. thanks

**Comment by thorsummoner** [comment]
i think the only option is to use the vmlinz chain loader, eg after booting
into the multiboot, from there boot into vmlinuz, and from there boot
Debian. this sucks though cause vmlinuz doesn't know where the iso's are
kept and you'll have to remember where to go and how to get there by hand
in the vmlinuz wizard.

also i think i had luck using the netboot mini.iso's from Debian (just had
to rename them to match the mbusb.d glob) and really, i should prefer a net
boot with a apt cache (i use squid-deb-proxy) witch works out well.

**Comment by mbusb** [comment]
Any of you tried booting Debian directly from ISO? Does the same issue occur in direct ISO booting as well?

**Comment by wijnand2** [comment]
Couldn't get the debian-9.3.0-amd64-netinst iso to work after making a bootable usb with unetbootin due to the error described in this issue. The workarounds suggested here didn't work either (possibly due to a lack of linux know-how but I did follow them to the best of my abilities). Ended up trying rufus 2.18 instead of unetbootin and used the 'Write in DD Image mode' option that is presented after clicking 'start'. This way I could install debian just fine.

**Comment by chewi** [comment]
I ran into this while trying to create a multiboot system that includes an installer for Kali. I installed the hd-media kernel and initrd.gz along with the ISO as documented. I found that it would work if I started a shell, umounted /media, and then retried. I guess it can't mount the USB device at /hd-media if it's already mounted at /media. Editing /usr/lib/fetch-url/file in the initrd to umount /media after copying the preseed file also made it work first time. I checked the initrd for Stretch and that file has not changed but the issue doesn't occur there anyway because I find that /hd-media is already correctly mounted. I don't know what's changed but I guess this fix will eventually make its way into Kali.

**Comment by rwuwon** [comment]
Should anyone still be encountering this - if Debian has been given some persistence storage in multibootusb, try uninstalling that and then redoing it, but with 0MB persistence - maybe that's more likely to work?

I remember having this issue with Tails (which is "built upon Debian") and similarly, I appear to have managed to avoid the "No common CD-ROM drive" message the second time around once I got rid of the persistence and the installer so far appears to progress onwards with my dry run.

Similarly, the ISO straight onto a blank USB also works for me.

debian-live-9.7.0-amd64-gnome.iso with MultiBootUSB 9.2.0 in Fedora 28.

**Comment by hollowaykeanho** [comment]
I'm experiencing the same issue today directly with Debian Buster netint ISO file, downloaded from https://www.debian.org/devel/debian-installer/

The funny workaround is this: https://www.youtube.com/watch?v=-F5E-qs93zQ

**Comment by katcaola** [comment]
I also had the same issue when installing [Debian Buster via the netinst ISO File](https://www.debian.org/CD/netinst/)

The video suggested by @hollowaykeanho worked like a charm.
For those too lazy to click the link:

> When you get to [the] point where it says 'your installation CD-rom couldn't be mounted', unplug 
> the USB from your computer drive and wait [a while].
> 
> [Then when it asks 'Retry mounting the CD-rom?' select 'No' and] click on continue
> 
> [Then select 'Detect and mount CD-rom' again from the menu and click Continue]
> 
> [When it goes back to the "Detect and mount CD-rom" header,] plug the USB back into the drive
> 
> Then click 'yes' to retry mounting the CD-rom [and] continue with [the] Installation


Also when it first says "Detect and Mount CD" in the header with no other text (immediately after you configure the keyboard) you can just quickly unplug and replug the USB device you're using into the same port and it should also find it right away.

**Comment by arafatx** [comment]
@hollowaykeanho Link to the youtube video is broken. Would love to see the funny workaround.
